spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1040087877/spring_cloud_factory/     # 配置git仓库的地址
          search-paths: spring-cloud-config-git/config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 1040087877@qq.com                           # git仓库的账号
          password: 3127586ABc                                  # git仓库的密码
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

management:
  security:
    enabled: false

server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址